# Generated by Django 4.1.8 on 2024-01-06 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='codepromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('estvalide', models.BooleanField()),
                ('estutilise', models.BooleanField()),
                ('dureevalidite', models.IntegerField()),
                ('dateexpiration', models.DateField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prixunitaire', models.IntegerField()),
                ('quantite', models.IntegerField()),
                ('prixtotal', models.IntegerField()),
                ('etat', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('codepromo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bonini.codepromo')),
            ],
        ),
        migrations.CreateModel(
            name='inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=50, null=True)),
                ('contact', models.CharField(max_length=50, null=True)),
                ('pays', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255, null=True)),
                ('estclient', models.BooleanField()),
                ('estinscriptparQR', models.BooleanField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='lemenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('prix', models.IntegerField()),
                ('reduction', models.IntegerField()),
                ('prixpromo', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='typemenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='menuvisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonini.inscription')),
                ('lemenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonini.lemenu')),
            ],
        ),
        migrations.AddField(
            model_name='lemenu',
            name='typemenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonini.typemenu'),
        ),
        migrations.CreateModel(
            name='facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pu_normal', models.IntegerField()),
                ('pu_promo', models.IntegerField()),
                ('quantite', models.IntegerField()),
                ('prixtotal_ligne_normal', models.IntegerField()),
                ('prixtotal_ligne_promo', models.IntegerField()),
                ('tva', models.IntegerField()),
                ('prixtotal_normal', models.IntegerField()),
                ('prixtotal_promo', models.IntegerField()),
                ('etat', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonini.commande')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='inscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonini.inscription'),
        ),
        migrations.AddField(
            model_name='commande',
            name='lemenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonini.lemenu'),
        ),
        migrations.AddField(
            model_name='codepromo',
            name='inscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonini.inscription'),
        ),
    ]
