# Generated by Django 4.1.8 on 2024-01-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonini', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemenu',
            name='estactif',
            field=models.BooleanField(default=1),
        ),
    ]
