# Generated by Django 4.1.8 on 2024-01-09 16:55

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('bonini', '0003_alter_inscription_pays_alter_lemenu_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='position_geographique',
            field=location_field.models.plain.PlainLocationField(max_length=63, null=True),
        ),
    ]
