# Generated by Django 4.1.8 on 2024-01-09 17:16

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('bonini', '0004_inscription_position_geographique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='position_geographique',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
    ]
