# Generated by Django 4.1.8 on 2024-01-11 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonini', '0006_stade'),
    ]

    operations = [
        migrations.CreateModel(
            name='niveaumatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_match', models.CharField(max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='commande',
            name='lemenu',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='prixunitaire',
        ),
        migrations.AddField(
            model_name='commande',
            name='ref',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='listematch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('equipe1', models.CharField(max_length=255)),
                ('equipe2', models.CharField(max_length=255)),
                ('dateheure', models.DateTimeField()),
                ('niveau_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonini.niveaumatch')),
            ],
        ),
        migrations.CreateModel(
            name='lematch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stade', models.CharField(max_length=255)),
                ('entree', models.CharField(max_length=50)),
                ('porte', models.CharField(max_length=50)),
                ('zone', models.CharField(max_length=50)),
                ('escalier', models.CharField(max_length=50)),
                ('bloc', models.CharField(max_length=50)),
                ('range', models.CharField(max_length=50)),
                ('siege', models.CharField(max_length=50)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonini.commande')),
                ('listematch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonini.listematch')),
            ],
        ),
        migrations.CreateModel(
            name='commande_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prixunitaire', models.IntegerField()),
                ('pu_promo', models.IntegerField()),
                ('quantite', models.IntegerField()),
                ('prixtotal', models.IntegerField()),
                ('prixtotal_ligne_promo', models.IntegerField()),
                ('etat', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonini.commande')),
                ('lemenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonini.lemenu')),
            ],
        ),
    ]
