# Generated by Django 4.1.8 on 2024-01-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonini', '0007_niveaumatch_remove_commande_lemenu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande_detail',
            name='etat',
        ),
        migrations.AddField(
            model_name='commande',
            name='estfacture',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='estclient',
            field=models.BooleanField(default=False),
        ),
    ]
