# Generated by Django 4.1.8 on 2024-01-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonini', '0010_rename_lematch_commende_match_listematch_estencours'),
    ]

    operations = [
        migrations.AddField(
            model_name='commende_match',
            name='trouve_sur_place',
            field=models.BooleanField(default=False),
        ),
    ]
