# Generated by Django 4.1.8 on 2024-01-11 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonini', '0011_commende_match_trouve_sur_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commende_match',
            old_name='range',
            new_name='rang',
        ),
    ]
