# Generated by Django 4.1.8 on 2024-01-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonini', '0012_rename_range_commende_match_rang'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='nbarticle',
            field=models.IntegerField(null=True),
        ),
    ]
