# Generated by Django 4.1.8 on 2024-01-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonini', '0014_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='ref',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
