# Generated by Django 4.1.8 on 2024-01-13 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonini', '0015_location_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu_stade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('estactif', models.BooleanField(default=1)),
                ('image', models.ImageField(upload_to='images/')),
                ('stade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonini.stade')),
            ],
        ),
    ]
