# Generated by Django 4.1.8 on 2024-01-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonini', '0017_menu_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_restaurant',
            name='stade',
        ),
    ]
