# Generated by Django 4.1.8 on 2024-01-18 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonini', '0018_remove_menu_restaurant_stade'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='stade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bonini.stade'),
        ),
    ]
