# Generated by Django 4.1.8 on 2024-01-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonini', '0020_gallerie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerie',
            name='estactif',
            field=models.BooleanField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='gallerie',
            name='estvideo',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
