# Generated by Django 4.1.8 on 2024-01-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonini', '0021_alter_gallerie_estactif_alter_gallerie_estvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerie',
            name='estactif',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='gallerie',
            name='estvideo',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='gallerie',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='gallerie',
            name='video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
