# Generated by Django 4.1.8 on 2024-01-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonini', '0022_alter_gallerie_estactif_alter_gallerie_estvideo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='gallerie',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
